services:
  - type: web
    name: aces-frontend
    runtime: node
    rootDir: Forum__Installation
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://aces-backkend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: aces-backkend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
