import asyncio
from sqlalchemy import select
from database import AsyncSessionLocal
from models import CommitteeMember

COMMITTEE_DATA = [
    {"key": "president", "role": "President", "name": "Atharv Thakare", "image": "/Atharv_Thakare.png", "linkedin": "https://www.linkedin.com/in/atharv-thakare-894140352", "github": "https://github.com/Atharv226", "bio": "Motivated Computer Engineering student with a passion for leadership, innovation, and student development. Dedicated to fostering collaboration, organizing impactful initiatives, and creating opportunities that inspire growth, teamwork, and excellence within the student community.", "skills": ["Leadership & Decision Making", "Team Management & Coordination", "Event Planning & Organization", "Communication & Public Speaking", "Strategic Planning & Student Engagement"], "projects": [{"title": "Campus Connect", "desc": "Built a secure online voting platform for campus elections with user authentication and result visualization."}, {"title": "RehabSync AI – Intelligent Rehabilitation System", "desc": "AI-powered rehabilitation system."}], "certificates": ["/Atharv_Achievement1.jpeg", "/Atharv_Achievement2.jpeg"], "achievements": [{"title": "Winner", "desc": "CODEHUNT 24-Hour Hackathon (1st year)"}, {"title": "Top 10 Finalist", "desc": "CHI 3.0 Innovation Challenge (2nd Year)"}], "experience": [{"role": "President", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Social Media Coordinator", "company": "ACES Forum, SCET", "duration": "2025-2026"}], "display_order": 1},
    {"key": "vice-president", "role": "Vice President", "name": "Madhura Vairagade", "image": "/Madhura_Vairagde.jpeg", "linkedin": "https://www.linkedin.com/in/madhuraa-vairagade-4b1174368/", "bio": "Madhura Vairagade is a dedicated Computer Engineering student serving as the Vice President of ACES. She supports the President in leading the association, coordinating committee activities, and organizing technical, cultural, and professional events.", "skills": ["Leadership & Strategic Planning", "Team Management & Coordination", "Event Planning & Execution", "Decision-Making & Problem Solving", "Communication & Student Engagement"], "experience": [{"role": "Vice President", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Documentation Head", "company": "Aces Forum", "duration": "2025 - 2026"}], "achievements": [], "certificates": [], "projects": [], "display_order": 2},
    {"key": "secretary", "role": "Secretary", "name": "Ajay Rathod", "image": "/Ajay_Rathod1.png", "linkedin": "https://www.linkedin.com/in/ajay-rathod-033625423", "github": "https://github.com/AjayRathod2012", "bio": "Ajay Rathod is a dedicated Computer Engineering student serving as the Secretary of ACES.", "skills": ["Leadership & Team Coordination", "Organizational & Administrative Management", "Communication & Public Relations", "Event Planning & Execution", "Documentation & Record Management"], "experience": [{"role": "Secretary", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Treasurer coordinator", "company": "Aces forum", "duration": "2025 - 2026"}], "certificates": ["/Ajay_Achievement1.jpeg"], "achievements": [], "projects": [], "display_order": 3},
    {"key": "treasurer", "role": "Treasurer", "name": "Yatharth Donarkar", "image": "/Yatharth_Donarkar.jpeg", "linkedin": "https://www.linkedin.com/in/yatharth-donarkar-662549350/", "github": "https://github.com/yatharthdonarkar2006", "email": "mailto:yatharthdonarkar13@gmail.com", "bio": "Computer Engineering Student | T&P Coordinator at Suryodaya College of Engineering and Technology | Hackathon Enthusiast.", "skills": [], "experience": [{"role": "Student Training and Placement Coordinator", "company": "Suryodaya College of Engineering and Technology", "duration": ""}, {"role": "Treasurer", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Technical Coordinator", "company": "ACES Forum, SCET", "duration": "2025-2026"}], "projects": [{"title": "AI-Based Resume Screening Tool", "desc": "Developed an AI-powered tool to automatically analyze and shortlist resumes."}, {"title": "NeuroGestureX – AI-Powered Rehabilitation System", "desc": "AI-powered system."}], "certificates": ["/Yatharth_Achievement.jpeg", "/Yatharth_Achievement1.jpeg", "/Yatharth_Achievement2.jpeg"], "achievements": [{"title": "Team Lead", "desc": "Training & Placement Coordinator at SCET"}, {"title": "Winner", "desc": "CODEHUNT 24-Hour Hackathon (1st year)"}, {"title": "Top 10 Finalist", "desc": "CHI 3.0 Innovation Challenge (2nd Year)"}], "display_order": 4},
    {"key": "technical-head", "role": "Technical Head", "name": "Sakshi Charlewar", "image": "/Sakshi_charlewar.png", "linkedin": "https://www.linkedin.com/in/sakshi-charlewar-39733234b", "github": "https://github.com/sakshicharlewar", "bio": "Passionate and dedicated Technical Head with strong leadership and problem-solving skills.", "skills": ["Technical Leadership", "Full Stack Web Development", "Project Planning & Team Management", "Problem Solving & Innovation", "Collaboration & Technical Mentoring"], "projects": [{"title": "CampusVote – Secure Digital Voting Platform", "desc": "Engineered a secure and high-performance digital voting platform."}, {"title": "Spectra-X", "desc": "AI and Blockchain-powered platform for detecting illegal mining."}], "achievements": [{"title": "Winner", "desc": "CODEHUNT 24-Hour Hackathon (1st year)"}, {"title": "Top 10 Finalist", "desc": "CHI 3.0 Innovation Challenge (2nd Year)"}], "certificates": ["/Sakshi_Achievement1.jpeg", "/Sakshi_Achievement2.jpeg"], "experience": [{"role": "Technical Head", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Technical Member", "company": "ACES Forum", "duration": "2025 - 2026"}], "display_order": 5},
    {"key": "cultural-head", "role": "Cultural Head", "name": "Kanak Nagose", "image": "/Kanak_Nagose.png", "linkedin": "https://www.linkedin.com/in/kanak-nagose-169491352", "github": "https://github.com/KanakNagose2007", "experience": [{"role": "Cultural Head", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Cultural Coordinator", "company": "ACES Forum", "duration": "2025 - 2026"}], "projects": [{"title": "Campus vote", "desc": "Secure voting platform."}, {"title": "RehabSync AI", "desc": "Rehabilitation system."}], "certificates": ["/Kanak_Achievement1.jpeg", "/Kanak_Achievement2.jpeg"], "achievements": [{"title": "Winner", "desc": "CODEHUNT 24-Hour Hackathon (1st year)"}, {"title": "Top 10 Finalist", "desc": "CHI 3.0 Innovation Challenge (2nd Year)"}], "skills": [], "bio": "", "display_order": 6},
    {"key": "magazine-head", "role": "Magazine Committee Head", "name": "Gaytri Kadu", "image": "/Gaytri_Kadu.png", "bio": "Gaytri Kadu is a dedicated Computer Engineering student serving as the Magazine Committee Head of ACES.", "skills": ["Editorial & Content Management", "Creative Writing & Proofreading", "Publication Design & Coordination", "Communication & Team Collaboration", "Content Planning & Organization"], "experience": [], "projects": [], "achievements": [], "certificates": [], "display_order": 7},
    {"key": "sports-head", "role": "Sports Head", "name": "Soham Runghe", "image": "/Soham_Runghe.jpeg", "bio": "Soham Runghe is a dedicated Computer Engineering student serving as the Sports Head of ACES.", "skills": ["Sports Event Planning & Management", "Team Leadership & Coordination", "Student Engagement & Motivation", "Teamwork & Collaboration", "Organizational & Communication Skills"], "experience": [], "projects": [{"title": "Mediflow – AI Powered Hospital Queue Optimizer", "desc": "AI-powered hospital queue optimization system."}], "achievements": [{"title": "1st Position – University Tug of War 2025", "desc": "Acquired 1st position in University Tug of War Match 2025."}, {"title": "1st Position – YCCE Tug of War 2026", "desc": "Acquired 1st position in Tug of War at YCCE 2026."}, {"title": "1st Position – KDK Tug of War 2026", "desc": "Acquired 1st position in Tug of War at KDK 2026."}, {"title": "Cyclothon – Nagpur 2023", "desc": "Successfully completed a 25 km Cyclothon in Nagpur 2023."}], "certificates": ["/Soham_Achievement1.jpeg", "/Soham_Achievement2.jpeg", "/Soham_Achievement3.jpeg", "/Soham_Achievement4.jpeg"], "display_order": 8},
    {"key": "rd-head", "role": "R&D Head", "name": "Tushar Kherde", "image": "/Tushar_Kherde1.png", "linkedin": "https://www.linkedin.com/in/tushar-kherde-2a651b332/", "github": "https://github.com/TusharKherde", "projects": [], "achievements": [], "certificates": [], "skills": [], "experience": [], "bio": "", "display_order": 9},
    {"key": "iic-head", "role": "IIC Head", "name": "Pravin Bangar", "image": "/Pravin_Bangar.png", "linkedin": "https://www.linkedin.com/in/pravin-bangar-616471359", "github": "https://share.google/5XqYTCw4VbmzmeeYF", "bio": "Pravin Bangar is a dedicated Computer Engineering student serving as the IIC Head of ACES.", "skills": ["Innovation & Entrepreneurship", "Leadership & Team Coordination", "Workshop & Event Management", "Creative Problem Solving", "Industry & Innovation Collaboration"], "experience": [{"role": "IIC Head", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Social media coordinator", "company": "Aces forum", "duration": "2025 - 2026"}], "projects": [{"title": "AI ATTENDANCE SYSTEM", "desc": "Automated attendance tracking."}, {"title": "Sharing plates", "desc": "Food sharing platform."}], "achievements": [{"title": "3rd Rank", "desc": "Power BI workshop at SCET"}, {"title": "5th Rank", "desc": "Datathon in P.R. Pote Patil College"}], "certificates": ["/Pravin_Achievement1.jpeg", "/Pravin_Achievement2.jpeg"], "display_order": 10},
    {"key": "edc-head", "role": "EDC Head", "name": "Om Kawale", "image": "/Om_Kawale.png", "linkedin": "https://www.linkedin.com/in/omkawale/", "bio": "Om Kawale is a dedicated Computer Engineering student serving as the EDC Head of ACES.", "skills": ["Entrepreneurship & Startup Development", "Leadership & Team Coordination", "Innovation & Business Strategy", "Industry Networking & Collaboration", "Event Planning & Program Management"], "experience": [{"role": "EDC Head", "company": "ACES Forum, SCET", "duration": "2026-2027"}, {"role": "Student Training and Placement Coordinator", "company": "SCET", "duration": "2025-2026"}], "projects": [], "achievements": [{"title": "Student Training and Placement Coordinator", "desc": "Served as T&P Coordinator at SCET."}], "certificates": ["/Om_Achievement1.jpeg"], "display_order": 11},
    {"key": "alumni-head", "role": "Alumni Head", "name": "Bhagyashree Thakare", "image": "/Bhagyashree_Thakare.png", "linkedin": "https://www.linkedin.com/in/bhagyashri-thakre-121a52318", "bio": "Bhagyashree Thakare is a dedicated Computer Engineering student serving as the Alumni Head of ACES.", "skills": ["Alumni Relations & Networking", "Communication & Relationship Management", "Event Planning & Coordination", "Leadership & Community Engagement", "Mentorship & Professional Networking"], "experience": [], "projects": [], "achievements": [], "certificates": ["/Bhagyashree_Achievement1.jpeg", "/Bhagyashree_Achievement2.jpeg"], "display_order": 12},
    {"key": "girls-rep", "role": "Girls Representative Head", "name": "Akansha Adhau", "image": "/Akansha_Adhau.jpeg", "linkedin": "https://www.linkedin.com/in/aakansha-adhau-517b52401", "github": "https://github.com/aakanshaadhau07", "bio": "Akansha Adhau is a passionate Computer Engineering student serving as the Girls Representative Head of ACES.", "skills": ["Student Representation & Advocacy", "Leadership & Team Coordination", "Event Planning & Student Engagement", "Communication & Public Relations", "Women Empowerment & Community Building"], "experience": [], "projects": [], "achievements": [{"title": "Ideathon Participant", "desc": "Participated in Ideathon at SCET."}, {"title": "National Conference Presenter", "desc": "Presented at ICTTSEM-2026 at SCET."}], "certificates": ["/Akansha_Achievement1.jpeg", "/Akansha_Achievement2.jpeg"], "display_order": 13},
    {"key": "doc-head", "role": "Documentation Head", "name": "Krutika Yewale", "image": "/Krutika_Yewale.png", "linkedin": "https://www.linkedin.com/in/krutika-yewale-130abb400", "github": "https://github.com/KrutikaYewale", "bio": "Krutika Yewale is a dedicated Computer Engineering student serving as the Documentation Head of ACES.", "skills": ["Technical Documentation & Report Writing", "Content Organization & Record Management", "Event Documentation & Photography Coordination", "Attention to Detail & Accuracy", "Communication & Documentation Management"], "experience": [], "projects": [], "achievements": [{"title": "5th Position", "desc": "GH Raisoni College Sandbox."}, {"title": "1st Position", "desc": "Tug of War at YCCE."}, {"title": "1st Position", "desc": "Urja-2026 Sports Competition."}], "certificates": ["/Krutika_Achievement1.jpeg", "/Krutika_Achievement2.jpeg", "/Krutika_Achievement3.jpeg"], "display_order": 14},
    {"key": "social-media-head", "role": "Social Media Head", "name": "Pushpak Zade", "image": "/Pushpak_Zade1.jpeg", "linkedin": "https://www.linkedin.com/in/pushpak-zade-05346038b", "bio": "Pushpak Zade is a dedicated Computer Engineering student serving as the Social Media Coordinator of ACES.", "skills": ["Social Media Management", "Content Creation & Digital Branding", "Graphic Design & Visual Communication", "Digital Marketing & Audience Engagement", "Creative Communication & Campaign Planning"], "experience": [], "projects": [], "achievements": [{"title": "5th Position", "desc": "Sandbox hackathon at Raisoni."}], "certificates": ["/Pushpak_Achievement1.jpeg"], "display_order": 15},
    {"key": "executive-member", "role": "Executive Member", "name": "Shwetank Shende", "image": "/Shwetank_Shende.png", "bio": "Shwetank Shende is a dedicated Computer Engineering student serving as an Executive Member of ACES.", "skills": ["Team Collaboration & Coordination", "Event Planning & Execution", "Leadership & Responsibility", "Communication & Interpersonal Skills", "Problem Solving & Organizational Skills"], "experience": [], "projects": [], "achievements": [], "certificates": [], "display_order": 16},
]


async def seed():
    async with AsyncSessionLocal() as db:
        for data in COMMITTEE_DATA:
            existing = await db.execute(select(CommitteeMember).where(CommitteeMember.key == data["key"]))
            if existing.scalar_one_or_none():
                print(f"  Skipping {data['name']} (already exists)")
                continue
            member = CommitteeMember(**data)
            db.add(member)
            print(f"  Added {data['name']} ({data['role']})")
        await db.commit()
        print("✅ Committee data seeded successfully!")

if __name__ == "__main__":
    asyncio.run(seed())
