services:
  - type: web
    name: aces-frontend
    runtime: node
    rootDir: Forum__Installation
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://aces-backkend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
